#!/usr/bin/env python3
"""Install script for quarto4sbp.

Creates a ~/.local/bin/q4s shim that runs the CLI from the project's venv.
"""

import os
import sys
from pathlib import Path


def main() -> int:
    """Install the q4s shim to ~/.local/bin."""
    # Get project root (where this script lives)
    project_dir = Path(__file__).parent.resolve()

    # Verify we're in the correct project
    pyproject_path = project_dir / "pyproject.toml"
    if not pyproject_path.exists():
        print("Error: pyproject.toml not found.", file=sys.stderr)
        print(
            "Please run this script from the quarto4sbp project root.", file=sys.stderr
        )
        return 1

    # Verify it's the right project
    try:
        with open(pyproject_path) as f:
            content = f.read()
            if 'name = "quarto4sbp"' not in content:
                print(
                    "Error: This doesn't appear to be the quarto4sbp project.",
                    file=sys.stderr,
                )
                return 1
    except Exception as e:
        print(f"Error reading pyproject.toml: {e}", file=sys.stderr)
        return 1

    # Check that venv exists
    venv_dir = project_dir / ".venv"
    if not venv_dir.exists():
        print("Error: Virtual environment not found at .venv", file=sys.stderr)
        print("Please create it first with: uv venv", file=sys.stderr)
        return 1

    # Check that venv has the activate script
    venv_activate = venv_dir / "bin" / "activate"
    if not venv_activate.exists():
        print(
            f"Error: venv activation script not found at {venv_activate}",
            file=sys.stderr,
        )
        return 1

    # Create ~/.local/bin if it doesn't exist
    local_bin = Path.home() / ".local" / "bin"
    try:
        local_bin.mkdir(parents=True, exist_ok=True)
    except Exception as e:
        print(f"Error creating {local_bin}: {e}", file=sys.stderr)
        return 1

    # Create the shim script
    shim_path = local_bin / "q4s"
    shim_content = f"""#!/bin/bash
# quarto4sbp CLI shim
# Generated by install.py - do not edit manually
PROJECT_DIR="{project_dir}"
source "$PROJECT_DIR/.venv/bin/activate"
exec python -m quarto4sbp.cli "$@"
"""

    try:
        with open(shim_path, "w") as f:
            f.write(shim_content)
        # Make it executable
        shim_path.chmod(0o755)
    except Exception as e:
        print(f"Error writing shim to {shim_path}: {e}", file=sys.stderr)
        return 1

    # Check if ~/.local/bin is in PATH
    path_env = os.environ.get("PATH", "")
    local_bin_str = str(local_bin)
    in_path = local_bin_str in path_env.split(os.pathsep)

    # Print success message
    print(f"✓ Successfully installed q4s shim to {shim_path}")
    print()

    if not in_path:
        print("⚠ Warning: ~/.local/bin is not in your PATH")
        print()
        print("Add this line to your ~/.bashrc, ~/.zshrc, or equivalent:")
        print('    export PATH="$HOME/.local/bin:$PATH"')
        print()
        print("Then reload your shell or run:")
        print("    source ~/.bashrc  # or ~/.zshrc")
        print()

    print("Usage:")
    print("    q4s help")
    print("    q4s echo hello world")
    print()

    return 0


if __name__ == "__main__":
    sys.exit(main())
